What's the version of Pandas that you installed?

In [5]:
import pandas as pd
pd.__version__

'1.5.3'

Getting the data

In [6]:
df = pd.read_csv('dataset.csv', delimiter = ',')

Reading the data

In [7]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

2. How many columns are in the dataset?

In [8]:
df.shape

(20640, 10)

3. Which columns in the dataset have missing values?

In [9]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

4. How many unique values does the `ocean_proximity` column have?

In [10]:
df.ocean_proximity.nunique()

5

5. What's the average value of the `median_house_value` for the houses located near the bay?

In [11]:
df[df['ocean_proximity']== 'NEAR BAY'].median_house_value.mean()

259212.31179039303

6. 
Calculate the average of `total_bedrooms` column in the dataset.
Use the `fillna` method to fill the missing values in `total_bedrooms` with the mean value from the previous step.
Now, calculate the average of `total_bedrooms` again.
Has it changed?

Has it changed?

In [12]:
df.total_bedrooms.mean()

537.8705525375618

In [13]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [14]:
df['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace = True)

In [15]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [16]:
df.total_bedrooms.mean()

537.8705525375617

7. Value of the last element of w*

In [17]:
df['ocean_proximity']=='ISLAND'

0        False
1        False
2        False
3        False
4        False
         ...  
20635    False
20636    False
20637    False
20638    False
20639    False
Name: ocean_proximity, Length: 20640, dtype: bool

In [18]:
df[df['ocean_proximity']=='ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [19]:
X = df[df['ocean_proximity']=='ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']].values

In [20]:
X.shape

(5, 3)

In [21]:
XTX = X.dot(X.T)

In [22]:
XTX.shape

(5, 5)

In [23]:
XTX = (X.T).dot(X)

In [24]:
XTX.shape

(3, 3)

In [25]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [26]:
XTX_inv = np.linalg.inv(XTX)

In [27]:
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [28]:
XTX_inv.shape

(3, 3)

In [29]:
w = (XTX_inv).dot(X.T)

In [30]:
w

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [32]:
y = np.array([950, 1300, 800, 1000, 1300])

In [33]:
y.shape

(5,)

In [34]:
w.dot(y)

array([23.12330961, -1.48124183,  5.69922946])